// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.DAL;

#nullable disable

namespace Pokedex.DAL.Migrations
{
    [DbContext(typeof(PokedexContext))]
    [Migration("20240202122928_InitTables")]
    partial class InitTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttackPokemon", b =>
                {
                    b.Property<int>("AttacksId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonsNumero")
                        .HasColumnType("int");

                    b.HasKey("AttacksId", "PokemonsNumero");

                    b.HasIndex("PokemonsNumero");

                    b.ToTable("AttackPokemon");

                    b.HasData(
                        new
                        {
                            AttacksId = 1,
                            PokemonsNumero = 25
                        },
                        new
                        {
                            AttacksId = 2,
                            PokemonsNumero = 25
                        },
                        new
                        {
                            AttacksId = 1,
                            PokemonsNumero = 1
                        },
                        new
                        {
                            AttacksId = 1,
                            PokemonsNumero = 2
                        },
                        new
                        {
                            AttacksId = 3,
                            PokemonsNumero = 2
                        });
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Charge",
                            TypeId = 7
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fatal Foudre",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tranche Herbe",
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonNumero")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonNumero")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PokemonNumero = 25,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png"
                        },
                        new
                        {
                            Id = 2,
                            PokemonNumero = 1,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png"
                        },
                        new
                        {
                            Id = 3,
                            PokemonNumero = 2,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png"
                        },
                        new
                        {
                            Id = 4,
                            PokemonNumero = 3,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png"
                        },
                        new
                        {
                            Id = 5,
                            PokemonNumero = 4,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png"
                        },
                        new
                        {
                            Id = 6,
                            PokemonNumero = 5,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png"
                        },
                        new
                        {
                            Id = 7,
                            PokemonNumero = 6,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png"
                        },
                        new
                        {
                            Id = 8,
                            PokemonNumero = 7,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png"
                        },
                        new
                        {
                            Id = 9,
                            PokemonNumero = 8,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png"
                        },
                        new
                        {
                            Id = 10,
                            PokemonNumero = 9,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png"
                        },
                        new
                        {
                            Id = 11,
                            PokemonNumero = 10,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png"
                        },
                        new
                        {
                            Id = 12,
                            PokemonNumero = 11,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png"
                        },
                        new
                        {
                            Id = 13,
                            PokemonNumero = 12,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png"
                        },
                        new
                        {
                            Id = 14,
                            PokemonNumero = 13,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png"
                        },
                        new
                        {
                            Id = 15,
                            PokemonNumero = 14,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png"
                        },
                        new
                        {
                            Id = 16,
                            PokemonNumero = 15,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png"
                        },
                        new
                        {
                            Id = 17,
                            PokemonNumero = 16,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png"
                        },
                        new
                        {
                            Id = 18,
                            PokemonNumero = 17,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png"
                        },
                        new
                        {
                            Id = 19,
                            PokemonNumero = 18,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png"
                        },
                        new
                        {
                            Id = 20,
                            PokemonNumero = 19,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png"
                        },
                        new
                        {
                            Id = 21,
                            PokemonNumero = 20,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png"
                        },
                        new
                        {
                            Id = 22,
                            PokemonNumero = 21,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png"
                        },
                        new
                        {
                            Id = 23,
                            PokemonNumero = 22,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png"
                        },
                        new
                        {
                            Id = 24,
                            PokemonNumero = 23,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png"
                        },
                        new
                        {
                            Id = 25,
                            PokemonNumero = 24,
                            Url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png"
                        });
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Pokemon", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLegendary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Numero = 25,
                            IsLegendary = false,
                            Name = "Pikachu",
                            TypeId = 1
                        },
                        new
                        {
                            Numero = 1,
                            IsLegendary = false,
                            Name = "Bulbizarre",
                            TypeId = 4
                        },
                        new
                        {
                            Numero = 2,
                            IsLegendary = false,
                            Name = "Herbizarre",
                            TypeId = 4
                        },
                        new
                        {
                            Numero = 3,
                            IsLegendary = false,
                            Name = "Florizarre",
                            TypeId = 4
                        },
                        new
                        {
                            Numero = 4,
                            IsLegendary = false,
                            Name = "Salameche",
                            TypeId = 4
                        },
                        new
                        {
                            Numero = 5,
                            IsLegendary = false,
                            Name = "Reptincel",
                            TypeId = 4
                        },
                        new
                        {
                            Numero = 6,
                            IsLegendary = false,
                            Name = "Dracaufeu",
                            TypeId = 4
                        },
                        new
                        {
                            Numero = 7,
                            IsLegendary = false,
                            Name = "Carapuce",
                            TypeId = 2
                        },
                        new
                        {
                            Numero = 8,
                            IsLegendary = false,
                            Name = "Carabaffe",
                            TypeId = 2
                        },
                        new
                        {
                            Numero = 9,
                            IsLegendary = false,
                            Name = "Tortank",
                            TypeId = 2
                        },
                        new
                        {
                            Numero = 10,
                            IsLegendary = false,
                            Name = "Chenipan",
                            TypeId = 13
                        },
                        new
                        {
                            Numero = 11,
                            IsLegendary = false,
                            Name = "Chrysacier",
                            TypeId = 13
                        },
                        new
                        {
                            Numero = 12,
                            IsLegendary = false,
                            Name = "Papilusion",
                            TypeId = 13
                        },
                        new
                        {
                            Numero = 13,
                            IsLegendary = false,
                            Name = "Aspicot",
                            TypeId = 13
                        },
                        new
                        {
                            Numero = 14,
                            IsLegendary = false,
                            Name = "Coconfort",
                            TypeId = 13
                        },
                        new
                        {
                            Numero = 15,
                            IsLegendary = false,
                            Name = "Dardargnan",
                            TypeId = 13
                        },
                        new
                        {
                            Numero = 16,
                            IsLegendary = false,
                            Name = "Roucool",
                            TypeId = 18
                        },
                        new
                        {
                            Numero = 17,
                            IsLegendary = false,
                            Name = "Roucoups",
                            TypeId = 18
                        },
                        new
                        {
                            Numero = 18,
                            IsLegendary = false,
                            Name = "Roucarnage",
                            TypeId = 18
                        },
                        new
                        {
                            Numero = 19,
                            IsLegendary = false,
                            Name = "Rattata",
                            TypeId = 7
                        },
                        new
                        {
                            Numero = 20,
                            IsLegendary = false,
                            Name = "Rattatac",
                            TypeId = 7
                        },
                        new
                        {
                            Numero = 21,
                            IsLegendary = false,
                            Name = "Piafabec",
                            TypeId = 18
                        },
                        new
                        {
                            Numero = 22,
                            IsLegendary = false,
                            Name = "Rapasdepic",
                            TypeId = 18
                        },
                        new
                        {
                            Numero = 23,
                            IsLegendary = false,
                            Name = "Abo",
                            TypeId = 14
                        },
                        new
                        {
                            Numero = 24,
                            IsLegendary = false,
                            Name = "Arbok",
                            TypeId = 14
                        });
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Name = "ACIER"
                        },
                        new
                        {
                            Id = 9,
                            Name = "COMBAT"
                        },
                        new
                        {
                            Id = 10,
                            Name = "DRAGON"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EAU"
                        },
                        new
                        {
                            Id = 1,
                            Name = "ELECTRIK"
                        },
                        new
                        {
                            Id = 11,
                            Name = "FEE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FEU"
                        },
                        new
                        {
                            Id = 12,
                            Name = "GLACE"
                        },
                        new
                        {
                            Id = 13,
                            Name = "INSECTE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "NORMAL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PLANTE"
                        },
                        new
                        {
                            Id = 14,
                            Name = "POISON"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PSY"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ROCHE"
                        },
                        new
                        {
                            Id = 15,
                            Name = "SOL"
                        },
                        new
                        {
                            Id = 16,
                            Name = "SPECTRE"
                        },
                        new
                        {
                            Id = 17,
                            Name = "TENEBRE"
                        },
                        new
                        {
                            Id = 18,
                            Name = "VOL"
                        });
                });

            modelBuilder.Entity("AttackPokemon", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.Attack", null)
                        .WithMany()
                        .HasForeignKey("AttacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pokedex.DAL.Entities.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonsNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Attack", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.PokemonType", "Type")
                        .WithMany("Attacks")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Image", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.Pokemon", "Pokemon")
                        .WithOne("Image")
                        .HasForeignKey("Pokedex.DAL.Entities.Image", "PokemonNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Pokemon", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.PokemonType", "Type")
                        .WithMany("Pokemons")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Pokemon", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.PokemonType", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
