// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.DAL;

#nullable disable

namespace Pokedex.DAL.Migrations
{
    [DbContext(typeof(PokedexContext))]
    partial class PokedexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttackPokemon", b =>
                {
                    b.Property<int>("AttacksId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonsNumero")
                        .HasColumnType("int");

                    b.HasKey("AttacksId", "PokemonsNumero");

                    b.HasIndex("PokemonsNumero");

                    b.ToTable("AttackPokemon");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonNumero")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonNumero")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Pokemon", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLegendary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("TypeId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("AttackPokemon", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.Attack", null)
                        .WithMany()
                        .HasForeignKey("AttacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pokedex.DAL.Entities.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonsNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Attack", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.PokemonType", "Type")
                        .WithMany("Attacks")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Image", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.Pokemon", "Pokemon")
                        .WithOne("Image")
                        .HasForeignKey("Pokedex.DAL.Entities.Image", "PokemonNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Pokemon", b =>
                {
                    b.HasOne("Pokedex.DAL.Entities.PokemonType", "Type")
                        .WithMany("Pokemons")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.Pokemon", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("Pokedex.DAL.Entities.PokemonType", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
